[publish]
# The registry to publish to
registry = "https://registry.npmjs.org/"

# The access level to publish with
access = "public"

[test]
# Test discovery & execution root
root = "."

# Coverage configuration
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "tests/**",
  "node_modules/**"
]
